export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL = 'COMPLETE_ALL'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'

export const PROGRESS_TUTORIAL = 'PROGRESS_TUTORIAL';

export const ADVICE_STARTED = 'ADVICE_STARTED';
export const ADVICE_DONE = 'ADVICE_DONE';
export const ADVICE_FAILED = 'ADVICE_FAILED';